#MAP
TILE_SIZE = 16
SCREEN_HEIGHT = 320 #480
SCREEN_WIDTH = 600

SIDE_BAR_WIDTH = 120

BACKGROUND = 0
SCRORE_TILES = 1
PLAYGROUND = 2
DANGER = 3
MIDGROUND = 4
ANIMATION_LAYER = 5
INTERACTABLES = 6

##IMAGES
NO_TEXTURE = "./Images/No_texture.png"
DEFAULT_TEXTURE = "./Images/default_texture.png"


#PlLAYER
speed = 1  #(Pixels)
FALL_SPEED = 2
MAX_DIS_FALL = 6*16 #in pixels, for fall damage
STANDING = 0
RUNNING = 1
JUMPING = 2
DEAD = 3
JUMPDURATION = 60 #Frames

SCREEN_CENTRE = (15*TILE_SIZE,10*TILE_SIZE)

LEFT_B = SCREEN_CENTRE[0]-5*TILE_SIZE #LEFT_BORDER
RIGHT_B = SCREEN_CENTRE[0]+5*TILE_SIZE #RIGHT_BORDER
TOP_B = SCREEN_CENTRE[1]-5*TILE_SIZE #TOP_BORDER
BOTTOM_B = SCREEN_CENTRE[1]+5*TILE_SIZE #BOTTOM_BORDER


#Main Loop
INTRO = 0
MENU = 1
PLAY = 2
DEAD = 3

##Refrencses
#   @Map origen = top-left of map